### ISSUE TITLE
Delphi Compilation 10.3.1 Rio Community Edition

### ISSUE THREAD

**Issue by ghost** [DelphiClubItalia/PKCS7Extractor#1]
I have compiled the demo with the Compiler Delphi 10.3.1 Community edition, everything works correctly.
I used the L
[libeay32.zip](https://github.com/DelphiClubItalia/PKCS7Extractor/files/3114140/libeay32.zip)

ibeay32.dll taken from the PostgreSQL installation of Library version 1.0.2.q

**Comment by zizzo81** [comment]
Well that's a version we don't have right now.
Did you try building and running tests on both 32 and 64-bit archictectures?

**Comment by ghost** [comment]
I have compiled the demo with the compiler Delphi 10.3.1 Community edition 64 bit everything works correctly.
Libray Libeay64.dll 1.0.1t from openvpn
Grizzly63
